name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the main branch
  issue_comment:
    types: [created, edited] # Triggers when a comment is added or changed

jobs:
  deploy:
    # This ensures it runs either on push, or if the comment literally says "/deploy"
    if: github.event_name == 'push' || contains(github.event.comment.body, '/deploy') 
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
